# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Todo Dia Algo Novo
tagline:          'Diário de um aprendiz'
description:      'Um simples diário sobre o aprendizado de cada dia'
url:              http://pablodinella.github.io/
baseurl:          /

paginate:         5
