# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Todo dia algo novo
tagline:          'A Jekyll theme'
description:      'Um simples diário sobre o aprendizado de cada dia'
url:              http://pablodinella.github.io/
baseurl:          /

paginate:         5
